#ifndef VRP_H
#define VRP_H

/*

This file is part of VROOM.

Copyright (c) 2015-2025, Julien Coupey.
All rights reserved (see LICENSE).

*/

#include <algorithm>
#include <cstdint>
#include <mutex>
#include <numeric>
#include <ranges>
#include <set>
#include <thread>

#include "algorithms/heuristics/heuristics.h"
#include "algorithms/local_search/local_search.h"
#include "structures/vroom/eval.h"
#include "structures/vroom/input/input.h"
#include "structures/vroom/solution/solution.h"
#include "utils/log.h"
#include "structures/vroom/return_to_depot_with_undelivered.h"
namespace vroom {

/**
 * LLM: @brief Initializes an empty solution with routes for all vehicles.
 *
 * Creates initial empty routes for each vehicle and populates them with
 * user-provided steps if available in the input.
 *
 * @tparam Route Type of route object.
 * @param input Input problem instance.
 * @param init_assigned Output set of jobs assigned from initial routes.
 * @return Vector of initialized routes for all vehicles.
 */
template <class Route>
std::vector<Route> set_init_sol(const Input& input,
                                std::unordered_set<Index>& init_assigned) {
  std::vector<Route> init_sol;
  init_sol.reserve(input.vehicles.size());
  // BRUNO: bit puzzled that it creates RawRoutes instead of TWRoutes
  for (Index v = 0; v < input.vehicles.size(); ++v) {
    init_sol.emplace_back(input, v, input.zero_amount().size());
  }

  if (input.has_initial_routes()) {
    heuristics::set_initial_routes<Route>(input, init_sol, init_assigned);
  }

  return init_sol;
}

/**
 * LLM: @brief Context for managing parallel solution search processes.
 *
 * Stores shared data for multiple concurrent heuristic and local search runs,
 * including initial solutions, unassigned jobs, and solution quality indicators.
 * Thread-safe for parallel solution exploration.
 *
 * @tparam Route Type of route object.
 */
template <class Route> struct SolvingContext {
  // LLM: Set of jobs assigned in the initial solution. Computed by `set_init_sol`. Purpose: to track which jobs are already handled before heuristics start.
  std::unordered_set<Index> init_assigned;
  // LLM: The initial solution containing empty routes or user-defined routes. Computed by `set_init_sol`. Purpose: serves as the starting point for all heuristic searches.
  const std::vector<Route> init_sol;
  // LLM: Set of jobs not yet assigned to any route. Computed in the constructor by checking `init_assigned`. Purpose: the set of jobs that heuristics need to insert into routes.
  std::set<Index> unassigned;
  // LLM: Vector of vehicle indices. Computed in the constructor as a sequence 0..N. Purpose: used by heuristics to iterate over vehicles, potentially in different orders.
  std::vector<Index> vehicles_ranks;
  // LLM: Vector of solutions, one for each search thread. Initialized with `init_sol`. Purpose: stores the evolving solution for each parallel search run.
  // BRUNO: so there is not a solution class per se, just a vector of routes
  std::vector<std::vector<Route>> solutions;
  // LLM: Vector of solution indicators (cost, unassigned count, etc.). Initialized with size `nb_searches`. Purpose: stores quality metrics for each solution to easily find the best one.
  std::vector<utils::SolutionIndicators> sol_indicators;

  // LLM: Set of unique solution indicators found by heuristics. Purpose: used to detect duplicate solutions generated by different heuristics to avoid redundant local search.
  std::set<utils::SolutionIndicators> heuristic_indicators;
  // LLM: Mutex for `heuristic_indicators`. Purpose: ensures thread-safe access to the set of unique indicators.
  std::mutex heuristic_indicators_m;

  SolvingContext(const Input& input, unsigned nb_searches)
    : init_sol(set_init_sol<Route>(input, init_assigned)),
      vehicles_ranks(input.vehicles.size()),
      solutions(nb_searches, init_sol),
      sol_indicators(nb_searches) {

    // Deduce unassigned jobs from initial solution.
    std::ranges::copy_if(std::views::iota(0u, input.jobs.size()),
                         std::inserter(unassigned, unassigned.begin()),
                         [this](const Index j) {
                           return !init_assigned.contains(j);
                         });

    // Heuristics will operate on all vehicles.
    // BRUNO: vehicles_ranks is just [0, 1, 2, ..., num_vehicles-1]
    std::iota(vehicles_ranks.begin(), vehicles_ranks.end(), 0);
  }

  // BRUNO: RECORD the new solution in heuristic_indicators , returns false if it is already known
  bool heuristic_solution_already_found(unsigned rank) {
    assert(rank < sol_indicators.size());
    const std::scoped_lock<std::mutex> lock(heuristic_indicators_m);
    const auto [dummy, insertion_ok] =
      heuristic_indicators.insert(sol_indicators[rank]);
    return !insertion_ok;
  }
};

/**
 * LLM: @brief Executes a single heuristic + local search run.
 *
 * Applies the specified heuristic to construct an initial solution, then
 * improves it using local search. Handles time budget management and duplicate
 * solution detection.
 *
 * BRUNO: here "rank" is used as an id (index in the list of searches) and does not have scoring connnotations
 * 
 * @tparam Route Type of route object.
 * @tparam LocalSearch Type of local search algorithm.
 * @param input Input problem instance.
 * @param p Heuristic parameters for this run.
 * @param rank Index of this search run in the context. 
 * @param depth Local search depth.
 * @param search_time Time budget for this search run.
 * @param context Shared solving context.
 */
template <class Route, class LocalSearch>
void run_single_search(const Input& input,
                       const HeuristicParameters& p,
                       const unsigned rank,
                       const unsigned depth,
                       const Timeout& search_time,
                       SolvingContext<Route>& context) {
  DEBUG_LOG("run_single_search() rank:"<< rank<<" heuristic:"<< static_cast<int>(p.heuristic));

  const auto heuristic_start = utils::now();

  Eval h_eval;
  switch (p.heuristic) {
  case HEURISTIC::BASIC:
    h_eval = heuristics::basic<Route>(input,
                                      context.solutions[rank],
                                      context.unassigned,
                                      context.vehicles_ranks,
                                      p.init,
                                      p.regret_coeff,
                                      p.sort);
    break;
  case HEURISTIC::DYNAMIC:
    h_eval = heuristics::dynamic_vehicle_choice<Route>(input,
                                                       context.solutions[rank],
                                                       context.unassigned,
                                                       context.vehicles_ranks,
                                                       p.init,
                                                       p.regret_coeff,
                                                       p.sort);
    break;
  }

  if (!input.has_homogeneous_costs() && p.sort == SORT::AVAILABILITY) {
    // Worth trying another vehicle ordering scheme in
    // heuristic.
    std::vector<Route> other_sol = context.init_sol;

    Eval h_other_eval;
    switch (p.heuristic) {
    case HEURISTIC::BASIC:
      h_other_eval = heuristics::basic<Route>(input,
                                              other_sol,
                                              context.unassigned,
                                              context.vehicles_ranks,
                                              p.init,
                                              p.regret_coeff,
                                              SORT::COST);
      break;
    case HEURISTIC::DYNAMIC:
      h_other_eval =
        heuristics::dynamic_vehicle_choice<Route>(input,
                                                  other_sol,
                                                  context.unassigned,
                                                  context.vehicles_ranks,
                                                  p.init,
                                                  p.regret_coeff,
                                                  SORT::COST);
      break;
    }

    if (h_other_eval < h_eval) {
      context.solutions[rank] = std::move(other_sol);
    }
  }

  // Check if heuristic solution has been encountered before.
  context.sol_indicators[rank] =
    utils::SolutionIndicators(input, context.solutions[rank]);

  const auto heuristic_end = utils::now();

  if (context.heuristic_solution_already_found(rank)) {
    // Duplicate heuristic solution, so skip local search.
    return;
  }
  
  logSolution(input,context.solutions[rank],context.sol_indicators[rank]);
  Timeout ls_search_time;
  if (search_time.has_value()) {
    const auto heuristic_time =
      std::chrono::duration_cast<std::chrono::milliseconds>(heuristic_end -
                                                            heuristic_start);

    if (search_time.value() <= heuristic_time) {
      // No time left for local search!
      return;
    }

    ls_search_time = search_time.value() - heuristic_time;
  }

  // Local search phase.
  LocalSearch ls(input, context.solutions[rank], depth, ls_search_time);
  ls.run();
  // BRUNO: ensure no-undelivered-return-to-depot
  // INFO_LOG("vvvvvvvvvvvvvvvvvvvvvvvvvvvv local search "<<rank<<" completed vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv");
  // Route& r = context.solutions[rank][4];
  //  {
  //   INFO_LOG(""<<r.to_string(&input));
  //   if (r.is_return_to_depot_with_undelivered_jobs_no_insertion(input)){
  //     ERROR_LOG("no-undelivered-return-to-depot failed:"+r.to_string(&input));
  //     // just for debug
  //     r.is_return_to_depot_with_undelivered_jobs_no_insertion(input);
  //     throw std::runtime_error("no-undelivered-return-to-depot violation");
  //   }
  // }
  // INFO_LOG("^^^^^^^^^^^^^^^^^^^^^^^^");

  // Store solution indicators.
  context.sol_indicators[rank] = ls.indicators();
  logSolution(input,context.solutions[rank],context.sol_indicators[rank]);
}
template <class Route>
void logSolution(const Input& input,std::vector<Route> routes, utils::SolutionIndicators indicators){
  INFO_LOG(" solution has "<< routes.size() <<" routes "<< " eval:"<< indicators);
  for(unsigned int i=0; i<routes.size(); i++){
    INFO_LOG(" route "<< i <<": "<< routes[i].to_string(&input));
    INFO_LOG(" is_return_to_depot_with_undelivered_jobs_no_insertion:"<<is_return_to_depot_with_undelivered_jobs_no_insertion(input,&routes[i].route));
  } 
  
}

/**
 * LLM: @brief Abstract base class for Vehicle Routing Problem solvers.
 *
 * Provides the common framework for solving VRP variants (CVRP, VRPTW, TSP)
 * using parallel multi-start heuristic search with local optimization. Derived
 * classes specify the route type and local search algorithm appropriate for
 * their specific problem constraints.
 */
class VRP {
  // Abstract class describing a VRP (vehicle routing problem).
protected:
  // LLM: Reference to the input problem instance. Initialized in constructor. Purpose: provides access to all problem data (jobs, vehicles, matrix, etc.) throughout the solving process.
  const Input& _input;

  /**
   * LLM: @brief Solves the VRP using parallel multi-start heuristic search.
   *
   * Executes multiple heuristic runs in parallel, each followed by local search
   * optimization, and returns the best solution found. Automatically selects
   * appropriate heuristic parameters based on problem structure (homogeneous vs
   * heterogeneous locations). Thread-safe with configurable parallelism.
   *
   * @tparam Route Type of route object specific to the VRP variant.
   * @tparam LocalSearch Type of local search algorithm to apply.
   * @param nb_searches Number of independent heuristic runs to perform.
   * @param depth Local search exploration depth.
   * @param nb_threads Maximum number of threads to use for parallel solving.
   * @param timeout Optional time budget for the entire solving process.
   * @param homogeneous_parameters Heuristic configurations for homogeneous problems.
   * @param heterogeneous_parameters Heuristic configurations for heterogeneous problems.
   * @return Best solution found across all search runs.
   */
  template <class Route, class LocalSearch>
  Solution solve(
    unsigned nb_searches,
    const unsigned depth,
    const unsigned nb_threads,
    const Timeout& timeout,
    const std::vector<HeuristicParameters>& homogeneous_parameters,
    const std::vector<HeuristicParameters>& heterogeneous_parameters) const {

    
    INFO_LOG("*** solve() nb_searches:"<< nb_searches <<" nb_threads:"<< nb_threads);

    const auto& parameters = (_input.has_homogeneous_locations())
                               ? homogeneous_parameters
                               : heterogeneous_parameters;
    assert(nb_searches != 0);
    nb_searches =
      std::min(nb_searches, static_cast<unsigned>(parameters.size()));

    SolvingContext<Route> context(_input, nb_searches);

    std::exception_ptr ep = nullptr;
    std::mutex ep_m;

    const auto actual_nb_threads = std::min(nb_searches, nb_threads);
    assert(actual_nb_threads <= 32);
    std::counting_semaphore<32> semaphore(actual_nb_threads);

    Timeout search_time;
    DEBUG_LOG("timeout:"<< (timeout.has_value() ? "set" : "not set")); 
    if (timeout.has_value()) {
      // Max number of solving per thread.
      const auto dv = std::div(static_cast<long>(nb_searches),
                               static_cast<long>(actual_nb_threads));
      const unsigned max_solving_number = dv.quot + ((dv.rem == 0) ? 0 : 1);
      search_time = timeout.value() / max_solving_number;
    }

    auto run_solving = [&context,
                        &semaphore,
                        &search_time,
                        &parameters,
                        &timeout,
                        &ep,
                        &ep_m,
                        depth,
                        this](const unsigned rank) {
      semaphore.acquire();
      try {
        run_single_search<Route, LocalSearch>(_input,
                                              parameters[rank],
                                              rank,
                                              depth,
                                              search_time,
                                              context);
      } catch (...) {
        const std::scoped_lock<std::mutex> lock(ep_m);
        ep = std::current_exception();
       
      }
      semaphore.release();
    };

    std::vector<std::jthread> solving_threads;
    solving_threads.reserve(nb_searches);

    for (unsigned i = 0; i < nb_searches; ++i) {
      solving_threads.emplace_back(run_solving, i);
    }

    for (auto& t : solving_threads) {
      t.join();
    }

    if (ep != nullptr) {
      std::rethrow_exception(ep);
    }

    auto best_indic = std::min_element(context.sol_indicators.cbegin(),
                                       context.sol_indicators.cend());

    return utils::
      format_solution(_input,
                      context.solutions[std::distance(context.sol_indicators
                                                        .cbegin(),
                                                      best_indic)]);
  }

public:
  explicit VRP(const Input& input);

  virtual ~VRP();

  /**
   * LLM: @brief Solves the VRP instance with specified search parameters.
   *
   * Pure virtual method to be implemented by derived classes (CVRP, VRPTW, TSP).
   * Each variant provides its own route type and local search algorithm suited
   * to its specific constraints and optimization goals.
   *
   * @param nb_searches Number of independent heuristic runs to perform.
   * @param depth Local search exploration depth.
   * @param nb_threads Maximum number of threads to use for parallel solving.
   * @param timeout Optional time budget for the solving process.
   * @return Optimized solution for the problem instance.
   */
  virtual Solution solve(unsigned nb_searches,
                         unsigned depth,
                         unsigned nb_threads,
                         const Timeout& timeout) const = 0;
};

} // namespace vroom

#endif
